import { EnergyType } from './types';

// ABSOLUTE URL for Native Android App (CapacitorHttp handles CORS)
export const API_BASE_URL = 'https://pynhcx.jnu.edu.cn/IBSjnuweb/WebService/JNUService.asmx/';

// Crypto Constants
export const AES_KEY_STR = 'CetSoftEEMSysWeb';
export const AES_IV_HEX = '1934577290ABCDEF1264147890ACAE45';

// Fallback Rates (JNU Panyu)
export const RATES: Record<number, number> = {
  [EnergyType.ELEC]: 0.647,
  [EnergyType.COLD_WATER]: 2.82,
  [EnergyType.HOT_WATER]: 25.0
};

// Weather API Constants
export const WEATHER_API_ID = '10010578';
export const WEATHER_API_KEY = 'feda2d2bcc4e153b1b063a50760f82a4';

export const LABELS = {
  zh: {
    title: '暨南大学 IBS 水电查询',
    login: '登录',
    roomPlaceholder: '房间号 (如 T8201)',
    dashboard: '概览',
    records: '记录',
    trends: '趋势',
    settings: '设置',
    aiAnalysis: 'AI 分析',
    balance: '账户余额',
    totalCost: '总支出',
    electricity: '电费',
    coldWater: '冷水',
    hotWater: '热水',
    usage: '用量',
    price: '单价',
    cost: '费用',
    rechargeRecords: '充值记录',
    date: '日期',
    amount: '金额',
    type: '类型',
    loading: '加载中...',
    error: '错误',
    logout: '退出',
    generateSummary: '生成 AI 总结',
    apiKeyPlaceholder: 'API Key',
    apiUrlPlaceholder: 'API Base URL (例如 https://dashscope.aliyuncs.com/compatible-mode/v1)',
    darkMode: '暗黑模式',
    lightMode: '明亮模式',
    language: '语言',
    summaryTitle: '水电情况智能分析',
    loginSuccess: '登录成功',
    loginFail: '登录失败',
    networkError: '网络错误，请检查是否在校园网环境',
    demoMode: '演示模式 (无校园网)',
    demoNote: '注意：由于浏览器 CORS 限制，直连学校服务器可能失败。',
    enableAI: '启用 AI 分析',
    betaTag: 'Beta',
    aiConfig: 'AI 配置',
    save: '保存',
    saved: '已保存',
    general: '通用',
    aiDescription: '启用后，可使用 AI 模型分析您的用水用电习惯。',
    configureAi: '请在设置中配置 AI',
    aiProvider: 'AI 提供商',
    modelName: '模型名称',
    googleGemini: 'Google Gemini',
    openaiCompatible: 'OpenAI 兼容 (DashScope/DeepSeek等)',
    modelPlaceholder: '例如: qwen-plus, gemini-2.5-flash',
    baseUrlHint: '对于 OpenAI 兼容模式，请输入完整的 Base URL (不包含 /chat/completions)',
    refresh: '刷新',
    calculator: '充值计算器',
    calcTitle: '智能充值助手',
    calcDesc: '基于近期用量预测下次充值金额',
    roommates: '宿舍人数',
    daysToCover: '预计使用天数',
    generatePlan: '计算充值方案',
    copy: '复制',
    close: '关闭',
    estimatedToday: '今日 (预估)',
    showUnit: '显示用量',
    showMoney: '显示金额',
    currencyCNY: '人民币 (CNY)',
    currencyUSD: '美元 (USD)',
    monthPrev: '上个月',
    monthNext: '下个月',
    unitKwh: 'kWh',
    unitM3: 'm³',
    currencyLabel: '货币单位',
    trendAnalysisTitle: 'AI 趋势解读',
    generateAnalysis: '生成分析',
    analysisNotEnabled: '未启用 AI',
    analysisPlaceholder: '点击生成基于当前图表数据的智能分析报告。',
    regenerate: '重新生成',
    statusActive: '服务正常',
    statusRecommend: '建议充值',
    statusOffline: '已欠费',
    tryDemo: '试用演示模式',
    subsidyLabel: '补贴',
    statusLabel: '状态'
  },
  en: {
    title: 'JNU IBS Client',
    login: 'Login',
    roomPlaceholder: 'Room No. (e.g. T8201)',
    dashboard: 'Dashboard',
    records: 'Records',
    trends: 'Trends',
    settings: 'Settings',
    aiAnalysis: 'AI Analysis',
    balance: 'Balance',
    totalCost: 'Total Cost',
    electricity: 'Electricity',
    coldWater: 'Cold Water',
    hotWater: 'Hot Water',
    usage: 'Usage',
    price: 'Price',
    cost: 'Cost',
    rechargeRecords: 'Recharge Records',
    date: 'Date',
    amount: 'Amount',
    type: 'Type',
    loading: 'Loading...',
    error: 'Error',
    logout: 'Logout',
    generateSummary: 'Generate AI Summary',
    apiKeyPlaceholder: 'API Key',
    apiUrlPlaceholder: 'API Base URL (e.g. https://api.openai.com/v1)',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    summaryTitle: 'Utility AI Analysis',
    loginSuccess: 'Login Successful',
    loginFail: 'Login Failed',
    networkError: 'Network Error. Ensure you are on Campus Network.',
    demoMode: 'Demo Mode (No Network)',
    demoNote: 'Note: Direct API calls may fail due to browser CORS policies.',
    enableAI: 'Enable AI Analysis',
    betaTag: 'Beta',
    aiConfig: 'AI Configuration',
    save: 'Save',
    saved: 'Saved',
    general: 'General',
    aiDescription: 'Enable to use AI models to analyze your utility usage patterns.',
    configureAi: 'Configure AI in Settings',
    aiProvider: 'AI Provider',
    modelName: 'Model Name',
    googleGemini: 'Google Gemini',
    openaiCompatible: 'OpenAI Compatible',
    modelPlaceholder: 'e.g. gpt-4, gemini-2.5-flash',
    baseUrlHint: 'For OpenAI Compatible, enter the Base URL (excluding /chat/completions)',
    refresh: 'Refresh',
    calculator: 'Recharge Calc',
    calcTitle: 'Recharge Assistant',
    calcDesc: 'Forecast recharge amount based on usage',
    roommates: 'Roommates',
    daysToCover: 'Days to Cover',
    generatePlan: 'Calculate Plan',
    copy: 'Copy',
    close: 'Close',
    estimatedToday: 'Today (Est.)',
    showUnit: 'Show Usage',
    showMoney: 'Show Cost',
    currencyCNY: 'CNY (¥)',
    currencyUSD: 'USD ($)',
    monthPrev: 'Prev Month',
    monthNext: 'Next Month',
    unitKwh: 'kWh',
    unitM3: 'm³',
    currencyLabel: 'Currency',
    trendAnalysisTitle: 'AI Trend Analysis',
    generateAnalysis: 'Generate',
    analysisNotEnabled: 'AI Disabled',
    analysisPlaceholder: 'Tap to generate smart analysis based on current chart data.',
    regenerate: 'Regenerate',
    statusActive: 'Active',
    statusRecommend: 'Recommended to top up',
    statusOffline: 'Offline',
    tryDemo: 'Try Demo Mode',
    subsidyLabel: 'Subsidy',
    statusLabel: 'Status'
  }
};